//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkySchool3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline_Assessment
    {
        public int ID_Discipline_Assessment { get; set; }
        public int ID_Discipline { get; set; }
        public int ID_Lesson_Type { get; set; }
        public int ID_Student { get; set; }
        public int Assessment { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Lesson_Type Lesson_Type { get; set; }
        public virtual Student Student { get; set; }
    }
}
